name: build-deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: install the project dependencies
        run: npm install

      - name: Build
        run: npm run docs:build

      - name: rsync to info.skvidar.run
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: .vitepress/dist/
          REMOTE_HOST: info.skvidar.run
          REMOTE_USER: fyksen
          TARGET: /var/info.skvidar.run/
          SCRIPT_AFTER: |
            echo $RSYNC_STDOUT
